version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: spring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - spring-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer_container
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - postgres

networks:
  spring-network:
    driver: bridge

volumes:
  postgres_data: