server:
  port: 8001
  servlet:
    context-path: /api
  error:
    include-message: always
spring:
  application:
    name: api-spring-boot-jpa
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  docker:
    compose:
      stop:
        command: down


