server:
  port: 8001
  servlet:
    context-path: /api
  error:
    include-message: always
spring:
  application:
    name: apirest
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

